# Generated by Django 5.1 on 2024-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
