# Generated by Django 5.1 on 2024-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
